#!/usr/bin/env python
#-*-coding:utf-8-*-
import requests
import argparse
from secret import api_token

parser = argparse.ArgumentParser(description='Get userids from Toggl workspace.')
parser.add_argument('--wid', type=str, required = True)      # työtilan id
args = parser.parse_args()

r = requests.get(
  'https://www.toggl.com/api/v8/workspaces/%s/workspace_users' %(args.wid),
  auth = (api_token,'api_token')
)

response = r.json()

for i in response:
    print i[u'uid'], '|', i[u'name']
